// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPhlEyYohATW0sqppilKxdEFZzEduyXUs',
    appId: '1:626057676839:web:5d6ed2902627a6beffa602',
    messagingSenderId: '626057676839',
    projectId: 'fruit-hub-8d28a',
    authDomain: 'fruit-hub-8d28a.firebaseapp.com',
    storageBucket: 'fruit-hub-8d28a.firebasestorage.app',
    measurementId: 'G-G6NXZSYGGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAag8PurJ_5sbzj8r3TYv0eTX0FMV7hMFI',
    appId: '1:626057676839:android:e4597c7990021c1affa602',
    messagingSenderId: '626057676839',
    projectId: 'fruit-hub-8d28a',
    storageBucket: 'fruit-hub-8d28a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5WgU7y9GUPgc-cWY6_N-uw5s8j8WHMkM',
    appId: '1:626057676839:ios:ed78e768f899da99ffa602',
    messagingSenderId: '626057676839',
    projectId: 'fruit-hub-8d28a',
    storageBucket: 'fruit-hub-8d28a.firebasestorage.app',
    iosBundleId: 'com.example.fruiteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5WgU7y9GUPgc-cWY6_N-uw5s8j8WHMkM',
    appId: '1:626057676839:ios:ed78e768f899da99ffa602',
    messagingSenderId: '626057676839',
    projectId: 'fruit-hub-8d28a',
    storageBucket: 'fruit-hub-8d28a.firebasestorage.app',
    iosBundleId: 'com.example.fruiteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPhlEyYohATW0sqppilKxdEFZzEduyXUs',
    appId: '1:626057676839:web:e72928925d47e8ffffa602',
    messagingSenderId: '626057676839',
    projectId: 'fruit-hub-8d28a',
    authDomain: 'fruit-hub-8d28a.firebaseapp.com',
    storageBucket: 'fruit-hub-8d28a.firebasestorage.app',
    measurementId: 'G-9HWTZ49RHG',
  );
}
